monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: critical
            handler:      buffered_critical
            excluded_http_codes: [404, 405]
        buffered_critical:
            type:    buffer
            handler: symfony_mailer
        symfony_mailer:
            type:       symfony_mailer
            from_email: ne-pas-repondre@cisirh.finances.gouv.fr
            to_email:   '%app.errors.to_email%'
            subject:    ERREUR %app.app_name% sur %app.environnement%
            level:      info
            formatter:          monolog.formatter.html
            content_type:       text/html
        main_error:
            type:         fingers_crossed
            action_level: error
            handler:      streamed
        streamed:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        login:
            type:     stream
            path:     "%kernel.logs_dir%/auth.log"
            level:    info
            channels: security