image: int.registry.docker.school-app:5000/docker:sock
services:
  - name: docker:dind
    alias: docker
   

stages:
  - Build
  - Security
  - Tests
  - Quality

################### STAGE 1 - BUILD ##################

build-vendor:
  image:
    name: jakzal/phpqa:php8.1
  stage: Build
  script:
    - mv .env.ci .env.local
    - apt-get update && apt-get install -y --no-install-recommends locales apt-utils git libicu-dev g++ libpng-dev libxml2-dev libzip-dev libonig-dev libxslt-dev unzip vim-tiny iputils-ping
    - echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
    - echo "fr_FR.UTF-8 UTF-8" >> /etc/locale.gen
    - locale-gen
    - docker-php-ext-configure intl
    - docker-php-ext-install pdo pdo_mysql intl zip calendar dom mbstring gd xsl
    - composer install
  allow_failure: false
  artifacts:
    untracked: true
  tags:
    - docker
    - int

################### STAGE 3 - TESTS ##################

phpunit:
  image:
    name: jakzal/phpqa:php8.1
  stage: Tests
  before_script:
    - export PANTHER_NO_HEADLESS=0
    - export PANTHER_NO_SANDBOX=1
    - export PANTHER_WEB_SERVER_PORT=9080
    - vendor/bin/bdi driver:geckodriver
  script:
    - php bin/phpunit
  allow_failure: true
  dependencies:
    - build-vendor
  tags:
    - docker
    - int


################### STAGE 4 - QUALITY ##################

phpcs:
  image:
    name: jakzal/phpqa:php8.1
  stage: Quality
  script:
    - phpcs -v --standard=PSR12 --ignore=./src/Kernel.php ./src
  allow_failure: true
  tags:
    - docker
    - int

phpstan:
  image:
    name: jakzal/phpqa:php8.1
  stage: Quality
  script:
    - phpstan analyse ./src
  allow_failure: false
  dependencies:
    - build-vendor
  tags:
    - docker
    - int

twig-lint:
  image:
    name: jakzal/phpqa:php8.1
  stage: Quality
  script:
    - php bin/console lint:twig templates/
  allow_failure: false
  tags:
    - docker
    - int
