<?php

namespace App\Repository;

use App\Entity\Utilisateur;
use Doctrine\ORM\EntityRepository;

/**
 * ConnexionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnexionRepository extends EntityRepository
{
    public function derniereConnexionUtilisateurs(Utilisateur $utilisateur, $maxResults = 10)
    {
        $qb = $this->createQueryBuilder('c')
        ->where('c.utilisateur = :utilisateur')
        ->orderBy('c.dateConnexion', 'DESC')
        ->setMaxResults($maxResults)
        ->setParameter('utilisateur', $utilisateur);

        return $qb->getQuery()->getResult();
    }
}
