<?php

declare(strict_types=1);

namespace App\Repository;

use App\Entity\Document;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * DocumentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Document::class);
    }

    public function getDocumentsAPurger()
    {
        $now = new \DateTime();
        $datePurge = $now->sub(new \DateInterval('PT1H'));

        $qb = $this->createQueryBuilder('d');
        $qb->where('d.brouillon = 1');
        $qb->andWhere('d.dateCreation < :datePurge');
        $qb->setParameter('datePurge', $datePurge);

        return $qb->getQuery()->getResult();
    }

    public function findOneDocumentBy($id)
    {
        $qb = $this->createQueryBuilder('d')
            ->where('d.id = :ID')
            ->setParameter('ID', $id);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
