<?php

namespace App\Repository;

use App\Entity\Utilisateur;
use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    // Cette requête est appelée par MessageManager :
    // Elle retourne l'ensemble des messages reçus et non lus par l'utilisateur en paramètre
    // Le manager est appelé dans index.base.html afin de mettre à jour la notif des messages

    public function findAllMessagesByUser(Utilisateur $user)
    {
        $qb = $this->createQueryBuilder('m')
                    ->where('m.destinataire = :user')
                    ->andWhere('m.lu = 0')
                    ->andWhere('m.supprime = 0')
                    ->setParameter('user', $user)
                    ->orderBy('m.dateEnvoi', 'DESC');

        $query = $qb->getQuery();

        return $query->getResult();
    }

    /* Cette requête est appelée par indexAction de MessageController (pour gérer la pagination):
     * Elle permet de récupérer un nombre de messages ($limit), à partir d'un offset ($offset)
     */

    public function getMessageFromOffset(Utilisateur $user, $limit, $offset)
    {
        $qb = $this->createQueryBuilder('m')
                    ->where('m.destinataire = :user')
                    ->andWhere('m.supprime = 0')
                    ->setParameter('user', $user)
                    ->orderBy('m.dateEnvoi', 'DESC')
                    ->setMaxResults($limit)
                    ->setFirstResult($offset)
                    ;

        $query = $qb->getQuery();

        return $query->getResult();
    }

    /*
     * Cette requête permet de récupérer le nombre de messages reçus par un utilisateur (lus et non lus)
     *
     */

    public function getNbMessagesRecus(Utilisateur $user)
    {
        $qb = $this->createQueryBuilder('m')
        ->select('COUNT(m)')
        ->where('m.destinataire = :user')
        ->andWhere('m.supprime = 0')
        ->setParameter('user', $user);

        $query = $qb->getQuery();

        return $query->getSingleScalarResult();
    }

    /* Cette requête est appelée par favorisAction de MessageController (pour gérer la pagination):
     * Elle permet de récupérer un nombre de messages ($limit), à partir d'un offset ($offset)
     */

    public function getMessageFavorisFromOffset(Utilisateur $user, $limit, $offset)
    {
        $qb = $this->createQueryBuilder('m')
        ->where('m.destinataire = :user')
        ->andWhere('m.supprime = 0')
        ->andWhere('m.favoris = 1')
        ->setParameter('user', $user)
        ->orderBy('m.dateEnvoi', 'DESC')
        ->setMaxResults($limit)
        ->setFirstResult($offset);

        $query = $qb->getQuery();

        return $query->getResult();
    }

    /*
     * Cette requête permet de récupérer le nombre de messages favoris par un utilisateur (lus et non lus)
     *
     */

    public function getNbMessagesFavoris(Utilisateur $user)
    {
        $qb = $this->createQueryBuilder('m')
        ->select('COUNT(m)')
        ->where('m.destinataire = :user')
        ->andWhere('m.supprime = 0')
        ->andWhere('m.favoris = 1')
        ->setParameter('user', $user);

        $query = $qb->getQuery();

        return $query->getSingleScalarResult();
    }

    /* Cette requête est appelée par corbeilleAction de MessageController (pour gérer la pagination):
     * Elle permet de récupérer un nombre de messages ($limit), à partir d'un offset ($offset)
     */

    public function getMessageCorbeilleFromOffset(Utilisateur $user, $limit, $offset)
    {
        $qb = $this->createQueryBuilder('m')
        ->where('m.destinataire = :user')
        ->andWhere('m.supprime = 1')
        ->setParameter('user', $user)
        ->orderBy('m.dateEnvoi', 'DESC')
        ->setMaxResults($limit)
        ->setFirstResult($offset);

        $query = $qb->getQuery();

        return $query->getResult();
    }

    /*
     * Cette requête permet de récupérer le nombre de messages supprimés par un utilisateur (lus et non lus)
     *
     */

    public function getNbMessagesCorbeille(Utilisateur $user)
    {
        $qb = $this->createQueryBuilder('m')
        ->select('COUNT(m)')
        ->where('m.destinataire = :user')
        ->andWhere('m.supprime = 1')
        ->setParameter('user', $user);

        $query = $qb->getQuery();

        return $query->getSingleScalarResult();
    }

    /*
     * Cette requête permet de chercher le $motcle parmi les message reçu par le $user (recherche sur les objets et les expediteurs des mails)
     *
     */

    public function search(Utilisateur $user, $limit, $offset, $motcle, $supprime = null, $favoris = null)
    {
        $qb = $this->createQueryBuilder('m')
                    ->leftJoin('m.expediteur', 'u')
                    ->where('m.destinataire = :user')
                    ->andWhere('m.objetMessage LIKE :motcle OR u.nom LIKE :motcle OR u.nom LIKE :motcle OR u.prenom LIKE :motcle')
                    ->setParameter('user', $user)
                    ->setParameter('motcle', '%'.$motcle.'%')
                    ->orderBy('m.dateEnvoi', 'DESC')
                    ->setMaxResults($limit)
                    ->setFirstResult($offset);

        if ($favoris) {
            $qb->andWhere('m.favoris = :favoris')
               ->setParameter('favoris', $favoris);
        }

        if ($supprime) {
            $qb->andWhere('m.supprime = :supprime')
               ->setParameter('supprime', $supprime);
        }

        $query = $qb->getQuery();

        return $query->getResult();
    }

    /*
     * Cette requête permet calculer le nombre de messages trouvé lors d'une recherche sur $motcle parmi les message reçu par le $user (recherche sur les objets et les expediteurs des mails)
     *
     */

    public function getNbsearch(Utilisateur $user, $motcle, $supprime = null, $favoris = null)
    {
        $qb = $this->createQueryBuilder('m')
                    ->select('COUNT(m)')
                    ->leftJoin('m.expediteur', 'u')
                    ->where('m.destinataire = :user')
                    ->andWhere('m.supprime = :supprime')
                    ->andWhere('m.objetMessage LIKE :motcle OR u.nom LIKE :motcle OR u.nom LIKE :motcle OR u.prenom LIKE :motcle')
                    ->setParameter('user', $user)
                    ->setParameter('supprime', $supprime)
                    ->setParameter('motcle', '%'.$motcle.'%')
                    ->orderBy('m.dateEnvoi', 'DESC');

        if ($favoris) {
            $qb->andWhere('m.favoris = :favoris')
               ->setParameter('favoris', $favoris);
        }

        if ($supprime) {
            $qb->andWhere('m.supprime = :supprime')
               ->setParameter('supprime', $supprime);
        }

        $query = $qb->getQuery();

        return $query->getSingleScalarResult();
    }
}
